### ISSUE TITLE
没有调用GPU推理

### ISSUE THREAD

**Issue by WhalerO** [NaruseMioShirakana/MoeSS#11]
首先感谢作者，总体使用很方便，效果不错

但是我在运行时默认调用的是CPU，而不是GPU，请问这可能是什么原因导致的？
我使用的是SoVITS的模型，之前用Python推理时没有这个问题

**Comment by NaruseMioShirakana** [comment]
因为我这边主要就是面向纯CPU用户，实际上用GPU也可以，等后续发布GPU版本

**Comment by NaruseMioShirakana** [comment]
GPU已经支持，本Issue就此关闭
