### ISSUE TITLE
使用SoVits 未找到模型

### ISSUE THREAD

**Issue by xbclub** [NaruseMioShirakana/MoeSS#13]
配置文件：
```json
{
    "Folder" : "yue",
    "Name" : "yue",
    "Type" : "SoVits",
    "Symbol" : "_,.!?-~…AEINOQUabdefghijkmnoprstuvwyzʃʧʦ↓↑" ,
    "Cleaner" : "LowerCharacters",
    "Rate" : 22050,
    "Hop" : 0,
    "Hifigan": "hifigan",
    "SoVits3": true,
    "Hubert": "hubert",
    "Pndm" : 100,
    "MelBins" : 128,
    "Characters" : []
}
```
onnx文件：
![image](https://user-images.githubusercontent.com/33245941/217201704-5d2f7c9d-00e8-4ec0-8af0-d0fbc877ebe0.png)
界面提示：
![image](https://user-images.githubusercontent.com/33245941/217201812-1cc9f4b1-2eff-4b53-9d43-d150cdf55177.png)
请问是哪里我没有配置对吗？

**Comment by NaruseMioShirakana** [comment]
{
    "Folder" : "yue",
    "Name" : "yue",
    "Type" : "SoVits",
    "Symbol" : "" ,
    "Cleaner" : "",
    "Rate" : 32000,
    "Hop" : 0,
    "SoVits3": true,
    "Hubert": "hubert",
    "Characters" : ["yue"]
}

里面的Rate改成你的采样率，还有就是SoVits有角色Emb必须Characters里必须得有东西

**Comment by NaruseMioShirakana** [comment]
Hop不能为0，要设置为你的项目的Hop
