### ISSUE TITLE
加载插件失败，可能是插件文件不存在

### ISSUE THREAD

**Issue by martjay** [NaruseMioShirakana/MoeSS#14]
---------------------------
失败
---------------------------
加载插件失败，可能是插件文件不存在

---------------------------
确定   
![666666](https://user-images.githubusercontent.com/44982189/218294453-30994627-af61-402b-85d8-66c5a31b94fc.jpg)

---------------------------

**Comment by martjay** [comment]
下面是GPU版的

---------------------------
失败
---------------------------
加载模型失败，可能是配置文件有误或模型有误
D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1069 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "F:\M\DiffSinger\0\MoeSS\onnxruntime_providers_cuda.dll"

---------------------------
确定   
---------------------------
![777777](https://user-images.githubusercontent.com/44982189/218294661-ad5f56b8-dbc6-4a4d-9f58-6e810963629c.jpg)

**Comment by NaruseMioShirakana** [comment]
看完我Bilibili所有相关的视频，里面都有说

**Comment by martjay** [comment]
请问哪个视频有说到？太多了看不来
