### ISSUE TITLE
新版仍然无法使用

### ISSUE THREAD

**Issue by martjay** [NaruseMioShirakana/MoeSS#15]
前置包已经下完按说明解压。

CPU版加载模型后出现错误提示。
![666666](https://user-images.githubusercontent.com/44982189/219060496-0d0f7411-def7-4d6a-a26a-b01c56a1cd6c.jpg)

GPU版加载模型后没有错误提示，几秒后自己闪退。

**Comment by NaruseMioShirakana** [comment]
请仔细查看ReadMe中模型制作章节中对于Cleaner项目设置的描述
至于CUDA版本闪退，这一点在Release和视频之中均已强调

**Comment by martjay** [comment]
> 请仔细查看ReadMe中模型制作章节中对于Cleaner项目设置的描述 至于CUDA版本闪退，这一点在Release和视频之中均已强调

我是直接按照你的安装说明解压的，模型都是你提供的那两个，跟这个有关系吗？我下载了还需要改什么？
