### ISSUE TITLE
GPU版本无法使用，打开直接闪退

### ISSUE THREAD

**Issue by Zxis233** [NaruseMioShirakana/MoeSS#16]
已安装全部依赖+所有插件，CPU版本正常运行，GPU版本正常打开，选择模型后几秒钟闪退

**Comment by NaruseMioShirakana** [comment]
注意CUDA版本和Cudnn版本，CUDA有一个恶心人的特性就是哪个版本编译哪个版本使用，也就是说你用CUDA11编译的软件CUDA12，CUDA10就不能用了，CUDNN也是一样

**Comment by NaruseMioShirakana** [comment]
该问题是由CUDA版本引起，在Release页面已强调这一点，故关闭
