### ISSUE TITLE
vits 转 onnx能提供下思路吗？

### ISSUE THREAD

**Issue by tianyu06030020** [NaruseMioShirakana/MoeSS#5]
官方vits pth转换成onnx只能固定维度使用，设置dynamic_axes也不行，请问任意音频长度
你是怎么转换的？谢谢。

**Comment by NaruseMioShirakana** [comment]
拆开导出
Infer函数里面有5块：enc，emb，dp，flow和dec
其中除了dp之外都可以用通常的onnx导出方式导出
但是dp一直有问题，所以dp需要更深一层的拆分，dp又可以拆成3个还是4个
