### ISSUE TITLE
载入时提示加载模型失败

### ISSUE THREAD

**Issue by gdtiti** [NaruseMioShirakana/MoeSS#6]
载入模型后提示加载模型失败

**Comment by XPRAMT** [comment]
一樣
<img src="https://www.z4a.net/images/2023/01/21/-2023-01-21-135612.jpg" alt="-2023-01-21-135612.jpg" border="0" />

**Comment by NaruseMioShirakana** [comment]
> 一樣 ![-2023-01-21-135612.jpg](https://camo.githubusercontent.com/c70c0024f767983b8be1d6cf9ca43c15f07db8e91d07f8c78e8a4e083d1fe9c0/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032332f30312f32312f2d323032332d30312d32312d3133353631322e6a7067)

从另一个仓库下载hifigan模型放到hifigan文件夹里面

**Comment by NaruseMioShirakana** [comment]
> > 一樣 ![-2023-01-21-135612.jpg](https://camo.githubusercontent.com/c70c0024f767983b8be1d6cf9ca43c15f07db8e91d07f8c78e8a4e083d1fe9c0/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032332f30312f32312f2d323032332d30312d32312d3133353631322e6a7067)
> 
> 从另一个仓库下载hifigan模型放到hifigan文件夹里面

不对，不是另一个仓库，是release里面有一个早期版本是有hifigan模型的

**Comment by NaruseMioShirakana** [comment]
> 一樣 ![-2023-01-21-135612.jpg](https://camo.githubusercontent.com/c70c0024f767983b8be1d6cf9ca43c15f07db8e91d07f8c78e8a4e083d1fe9c0/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032332f30312f32312f2d323032332d30312d32312d3133353631322e6a7067)

在release的2.0.1 tag下有一个hifigan.7z，下载他，把里面的onnx模型放到hifigan文件夹下就可以了

**Comment by NaruseMioShirakana** [comment]
> 载入模型后提示加载模型失败

发一下报错（）

**Comment by XPRAMT** [comment]
hifigan的問題解決了，不過又出現新的錯誤
<img src="https://www.z4a.net/images/2023/01/22/-2023-01-22-211328.jpg" alt="-2023-01-22-211328.jpg" border="0" />

**Comment by NaruseMioShirakana** [comment]
> hifigan的問題解決了，不過又出現新的錯誤 ![-2023-01-22-211328.jpg](https://camo.githubusercontent.com/4edc357d4f5753876e024e09e895123e06da12d94da120094e69e9310c6bc2d9/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032332f30312f32322f2d323032332d30312d32322d3231313332382e6a7067)

把模型配置文件的cleaners那一项给换成空字符串

**Comment by Dashu-Li** [comment]
emmm……怎么训练模型？（我只是高中生，是小白，完全不知道怎么操作

**Comment by fhyuncai** [comment]
> 把模型配置文件的cleaners那一项给换成空字符串

```
{
    "Folder" : "Shiroha",
    "Name" : "鳴瀬しろは-Tacotron2",
    "Type" : "Tacotron2",
    "Symbol" : "_-!'(),.:;? ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
    "Cleaner" : "",
    "Rate" : 22050,
    "Hop" : 320,
    "Hifigan": "hifigan",
    "Characters" : []
}
```
这样还是提示 `加载插件失败`

**Comment by xbclub** [comment]
> > 把模型配置文件的cleaners那一项给换成空字符串
> 
> ```
> {
>     "Folder" : "Shiroha",
>     "Name" : "鳴瀬しろは-Tacotron2",
>     "Type" : "Tacotron2",
>     "Symbol" : "_-!'(),.:;? ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
>     "Cleaner" : "",
>     "Rate" : 22050,
>     "Hop" : 320,
>     "Hifigan": "hifigan",
>     "Characters" : []
> }
> ```
> 
> 这样还是提示 `加载插件失败`

我将JapaneseCleaner.dll放入了cleaners文件夹 也继续提示加载插件失败。。。。

**Comment by NaruseMioShirakana** [comment]
> > > 把模型配置文件的cleaners那一项给换成空字符串
> > 
> > 
> > ```
> > {
> >     "Folder" : "Shiroha",
> >     "Name" : "鳴瀬しろは-Tacotron2",
> >     "Type" : "Tacotron2",
> >     "Symbol" : "_-!'(),.:;? ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
> >     "Cleaner" : "",
> >     "Rate" : 22050,
> >     "Hop" : 320,
> >     "Hifigan": "hifigan",
> >     "Characters" : []
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样还是提示 `加载插件失败`
> 
> 我将JapaneseCleaner.dll放入了cleaners文件夹 cleaner配置JapaneseCleaner是成功的 看样子是没有LowerCharacters的dll组件，我建议维护者能整理下这些文件，目前这些文件散落在release的各个版本，得一个个翻

目前已将这些模型全部集成到了huggingface。
