### ISSUE TITLE
2.5.0版本，使用SoVits模型，转换文本时报无法创建ffmpeg任务

### ISSUE THREAD

**Issue by SixInternet** [NaruseMioShirakana/MoeSS#7]

**Comment by SixInternet** [comment]
![image](https://user-images.githubusercontent.com/53228262/213917294-c2877283-a7a2-4d1c-9233-2419dc0b6e7c.png)

**Comment by NaruseMioShirakana** [comment]
bins文件夹下有没有ffmpeg.exe

**Comment by NaruseMioShirakana** [comment]
由于新版本移除了FFmpeg exe，故本issue自此以后close
