### ISSUE TITLE
文字转语音过程出现Wav load error

### ISSUE THREAD

**Issue by yxxxxp** [NaruseMioShirakana/MoeSS#8]
![I$3YUAAF%IT6IRAE6R4L(Z3](https://user-images.githubusercontent.com/123443234/214227738-b0b2189f-98b7-4d77-b988-894e523515ce.png)

**Comment by NaruseMioShirakana** [comment]
SoVits的文字转语音是需要载入串联模型的，因为SoVits本身是不支持文字转语音的
