### ISSUE TITLE
MoeSS3.0使用SoVits模型转换语音时出现如下错误

### ISSUE THREAD

**Issue by yxxxxp** [NaruseMioShirakana/MoeSS#9]
![1S9}9DZ$2 H_1}{}SE0WHKE](https://user-images.githubusercontent.com/123443234/214561314-66c3a53a-8ea0-4255-9d42-270925289017.png)

**Comment by NaruseMioShirakana** [comment]
这个是由于SoVits3和SoVits2的的预处理方式以及f0数据类型不同造成的，SoVits3是float型f0但是SoVits2是long long型f0，而且这两个的预处理方式完全不同（到最后处理出来的f0差十万八千里）
这也就是我在视频中强调必须填写正确SoVits3那一项的原因。
这个报错解释一下就是输入了一个longlong型的f0（SoVits2的预处理方式），但是需要一个float型f0（SoVits3的预处理方式），所以解决这个问题的方法就是把模型配置文件的SoVits3设置为true。
确定你的配置文件写对了，如果用的是SoVits3.0必须吧SoVits3那个设置为true，不是的话必须是false。
